image: Visual Studio 2017
configuration: Release
platform: Any CPU
version: 1.0.{build}
clone_depth: 1

before_build:
  - nuget restore

build:
  verbosity: minimal

after_build:
  - 7z a windowswitcher.zip %APPVEYOR_BUILD_FOLDER%\\windowswitcher.app\bin\Release\*.*

artifacts:
  - path: windowswitcher.zip

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)

deploy:
  release: windowswitcher-v$(appveyor_build_version)
  description: windowswitcher-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: uG/EbklyR/JLrHlnpnBTnVFyY1o9i2A61ceZ2NjJMkFSQO+oORMADOx/+3AP1LkK
  artifact: /.*\.zip/
  draft: true
  on:
    branch: master
